#!/usr/bin/env node
'use strict';

var util = require('./util');

// Check current branch and commit message
function checkCommit() {
  util.getCurrentBranch()
    .then(util.getJiraIssue)
    .then(issue => {
      util.getCommitMessage(process.argv[2])
        .then(msg => {
          let reg = new RegExp('^' + issue, 'i');
          if (!reg.test(msg)) {
            throw new Error(`Commit message should include a reference to the JIRA-issue (${issue}).`);
          }
      });
    })
    .catch(error => {
      console.log('error: ' + error.message);
      process.exit(1);
    });
}

// Call
checkCommit();

