require("mini.bracketed").setup({
  buffer     = { suffix = 'b', options = {} },
  comment    = { suffix = 'c', options = {} },
  conflict   = { suffix = 'x', options = {} },
  diagnostic = { suffix = 'd', options = {} },
  quickfix   = { suffix = 'q', options = {} },
  file       = { suffix = '' },
  indent     = { suffix = '' },
  jump       = { suffix = '' },
  location   = { suffix = '' },
  oldfile    = { suffix = '' },
  treesitter = { suffix = '' },
  undo       = { suffix = '' },
  window     = { suffix = '' },
  yank       = { suffix = '' },
})
