# Taps
tap "1password/tap"
tap "adoptopenjdk/openjdk"
tap "bufbuild/buf"
tap "go-task/tap"
tap "goreleaser/tap"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "itsdalmo/tap"
tap "warrensbox/tap"

# Apps
cask "1password/tap/1password-cli"
cask "adoptopenjdk11"
cask "brave-browser"
cask "discord"
cask "docker"
cask "firefox"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "font-symbols-only-nerd-font"
cask "goland"
cask "google-cloud-sdk"
cask "intellij-idea"
cask "keybase"
cask "multipass"
cask "postman"
cask "rectangle"
cask "sensiblesidebuttons"
cask "signal"
cask "slack"
cask "spotify"
cask "visual-studio-code"
cask "wezterm"

# Packages
brew "aws-vault"
brew "awscli"
brew "bufbuild/buf/buf"
brew "exa"
brew "fd"
brew "fish"
brew "fisher"
brew "fzf"
brew "gh"
brew "go"
brew "go-task/tap/go-task"
brew "gofumpt"
brew "golangci-lint"
brew "goreleaser/tap/goreleaser"
brew "graphviz"
brew "helm"
brew "hugo"
brew "jq"
brew "jsonlint"
brew "kubectx"
brew "kubernetes-cli"
brew "kustomize"
brew "lazygit"
brew "mas"
brew "nvim"
brew "nvm"
brew "packer"
brew "prettier"
brew "protobuf"
brew "pyenv"
brew "pyenv-virtualenv"
brew "ripgrep"
brew "shellcheck"
brew "shfmt"
brew "stylua"
brew "tflint"
brew "typescript"
brew "vaulted"
brew "warrensbox/tap/tfswitch"
brew "yarn"
brew "zoxide"

# Mac store
mas "Agenda", id: 1287445660
mas "Microsoft Excel", id: 462058435
mas "Microsoft Powerpoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Xcode", id: 497799835
