# Git aware (color coded) prompt
export GITAWAREPROMPT=~/.bash/git-aware-prompt
source "${GITAWAREPROMPT}/main.sh"

# Git autocompletion
if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

# |21:36:02|user|~/Current/path(git_branch)>>>
export PS1="|\t|\u|\w\[$txtcyn\]\$git_branch\[$txtred\]\$git_dirty\[$txtrst\]>>> "

# Use ripgrep with FZF
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'

# Encoding
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Added by Homebrew installer for nvim
export NVM_DIR="~/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# Use nvim as the default editor
export EDITOR=nvim

# Use homebrew version of vim
alias vim='/usr/local/bin/vim'

# Tmux setting and shortcut
alias tmux="TERM=screen-256color-bce tmux"
function dev {
         tmux att -t ${PWD} || tmux new -s ${PWD} 'tmux source-file ~/.tmux/dev-session.config'
}
alias dev='dev'
alias ll='ls -la'

# Use FZF
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# AWS CLI setup
export EC2_HOME="/usr/local/ec2/ec2-api-tools-1.7.5.1"
export EC2_URL="ec2.eu-west-1.amazonaws.com"
export PATH="$PATH:$EC2_HOME/bin"
export JAVA_HOME="$(/usr/libexec/java_home)"

# Path
export PATH="//anaconda/bin:$PATH"
export PATH="$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin"
export PATH=/Library/Frameworks/GDAL.framework/Programs:$PATH
export GOPATH=$HOME/Github/test-go
export PATH=$GOPATH/bin:$PATH
export PATH=~/.cargo/bin:$PATH

