format = """
$directory\
$git_branch\
$git_state\
$kubernetes\
$azure\
$cmd_duration\
$line_break\
$username\
$hostname\
$character"""

[directory]
style = "blue"

[git_branch]
style = "bright-black"
symbol = ""

[git_state]
style = "bright-black"

[kubernetes]
disabled = false
format = "on [$symbol$context\\($namespace\\)]($style) "
style = "blue"

[azure]
disabled = false
format = "on [$symbol\\($subscription\\)]($style) "
style = "blue"

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[username]
format = "[$user]($style)"
style_user = "bright-black"


[hostname]
format = "[@$hostname]($style) "
style = "bright-black"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

