format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$cmd_duration\
$line_break\
$kubernetes\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style) "
style = "bright-black"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[kubernetes]
disabled = false
format = "[$context]($style) "
style = "bright-black"
